### ISSUE TITLE
Filenamer doesn't honor all its flags

### ISSUE THREAD

**Issue by ry99** [Ostrich-Emulators/PreVent#33]
the FileNamer has lots of options:
%p - patient ordinal
%i - input filename (without directory or extension)
%d - input directory
%x - input extension
%m - modified date of input file
%c - creation date of input file
%D - date of conversion
%s - date of first data point
%e - date of last data point
%o - output file ordinal
%t - the --to option's extension (e.g., hdf5, csv)
%s - the "standard" filenaming option (convenience for %i-p%p-%s.%t)

Some are implemented, and some aren't. They all need to be.

**Comment by mckorbon** [comment]
%c- creation date is not possible through Linux. Flag will be discarded
